# main
episodes: 3000
batch_size: 32 # trying 64 breakout 32 box
lr: .0001 #
gamma: .9 # 0.99

# epsilon-greedy
epsilon_min: .01
epsilon_decay: .995

# training
update_target: 1000 # both
warmup: 100
update_freq: 4
